# Generated by Django 4.0 on 2022-09-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteTvShows',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('poster_path', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('backdrop_path', models.TextField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('overview', models.TextField(null=True)),
                ('first_air_date', models.DateField(null=True)),
                ('origin_country', models.TextField(null=True)),
                ('genre_ids', models.TextField(null=True)),
                ('original_language', models.TextField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
                ('original_name', models.TextField(null=True)),
                ('media_type', models.TextField(null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteTvShow', to='auth.user')),
                ('watchlist', models.ForeignKey(db_column='watchlist_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.watchlist')),
            ],
            options={
                'db_table': 'favorite_tv_shows',
            },
        ),
        migrations.CreateModel(
            name='FavoriteMovieShows',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('poster_path', models.TextField(null=True)),
                ('adult', models.BooleanField(default=False)),
                ('overview', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('genre_ids', models.TextField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_title', models.TextField(null=True)),
                ('original_language', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('backdrop_path', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField(null=True)),
                ('media_type', models.TextField(null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteMovieShow', to='auth.user')),
                ('watchlist', models.ForeignKey(db_column='watchlist_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.watchlist')),
            ],
            options={
                'db_table': 'favorite_movie_shows',
            },
        ),
    ]
