# Generated by Django 4.0 on 2022-09-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_watchlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovieshows',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='favoritetvshows',
            name='tv_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='favoritemovieshows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favoritetvshows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
