# Generated by Django 4.0 on 2022-09-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_watchlistmovieapilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistmovieapilog',
            name='response_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
